name: Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: NuGet/setup-nuget@v3.0.0
      - name: Pack nuget
        run: nuget pack package -OutputFileNamesWithoutVersion -OutputDirectory build -Properties "git=https://github.com/${{ github.repository }}.git;name=${{ github.event.repository.name }};author=${{ github.repository_owner }};description=${{ github.event.repository.description }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ github.event.repository.name }}
          path: build/${{ github.event.repository.name }}.nupkg
      - name: Publish NuGet
        run: |
          nuget push "build/${{ github.event.repository.name }}.nupkg" -ApiKey ${{ secrets.NUGET_KEY }} -Source https://api.nuget.org/v3/index.json
      - name: Publish to GitHub Packages
        run: |
          nuget push "build/${{ github.event.repository.name }}.nupkg" -ApiKey ${{ secrets.GITHUB_TOKEN }} -Source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
